# Generated by Django 3.2.7 on 2024-06-28 13:03

from django.db import migrations, models
import django.db.models.deletion
import time_stamped_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_pdf_examples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_pdf_examples.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=1024)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_pdf_examples.invoice')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
